apiVersion: v1
data:
  countme.yaml: |
    database:
      hostname: {{ .Release.Name }}-redis.default.svc.cluster.local
      port: 6379
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-countme
  namespace: default
