apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-countme
  labels:
    app: countme
    release: {{ .Release.Name }}
spec:
  selector:
    app: countme
    release: {{ .Release.Name }}
  ports:
  - protocol: "TCP"
    port: 8000
  type: ClusterIP
